name: Azure Web App Java CI/CD

env:
  AZURE_WEBAPP_NAME: spring-cicd-pipline
  JAVA_VERSION: '21'  # Added quotes around version number

on:
  push:
    branches:
      - main
  pull_request:  # Fixed: removed extra indentation and dash
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests
        run: mvn clean test

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload Artifact for Deployment Job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to Azure Web App
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'